services:
  - type: web
    name: linkedin-watcher
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python web_app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATA_DIR
        value: /var/data
    disks:
      - name: data
        mountPath: /var/data
        sizeGB: 1
    autoDeploy: true

